### ISSUE TITLE
Skin shuffle crashes

### ISSUE THREAD

**Issue by Ggsgshhshs** [IMB11-Mods/SkinShuffle#96]
### Describe the issue

Log: - skinshuffle 2.0.4+1.20.4
	   |-- cicada 0.8.0+1.20.2-1.20.4
	   |-- com_konghq_unirest-java_standalone 3.11.9
	   |-- commons-validator_commons-validator 1.7
	   |-- org_jsoup_jsoup 1.16.1
	   |-- org_mineskin_java-client 1.2.4-SNAPSHOT
	   |-- spruceui 5.0.3+1.20.4
	   \-- yet_another_config_lib_v3 3.5.0+1.20.4-fabric
	        |-- com_twelvemonkeys_common_common-image 3.10.0
	        |-- com_twelvemonkeys_common_common-io 3.10.0
	        |-- com_twelvemonkeys_common_common-lang 3.10.0
	        |-- com_twelvemonkeys_imageio_imageio-core 3.10.0
	        |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0
	        |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0
	        |-- org_quiltmc_parsers_gson 0.2.1
	        \-- org_quiltmc_parsers_json 0.2.1
[11:01:47] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/ivsor.DESKTOP-CNQ36NN/AppData/Roaming/.tlauncher/legacy/Minecraft/game/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[11:01:47] [main/INFO]: Compatibility level set to JAVA_17
[11:01:48] [main/WARN]: Error loading class: com/provismet/provihealth/util/Visibility (java.lang.ClassNotFoundException: com/provismet/provihealth/util/Visibility)
[11:01:48] [main/WARN]: Error loading class: net/tslat/tes/api/util/TESUtil (java.lang.ClassNotFoundException: net/tslat/tes/api/util/TESUtil)
[11:01:48] [main/WARN]: Error loading class: org/jetbrains/annotations/ApiStatus$Internal (java.lang.ClassNotFoundException: org/jetbrains/annotations/ApiStatus$Internal)
[11:01:48] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[11:01:52] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 163 milliseconds
[11:01:53] [Render thread/INFO]: Environment: ElyEnvironment[name=ely,authHost=https://authserver.ely.by/auth,accountsHost=https://account.ely.by/api/mojang,sessionHost=https://account.ely.by/api/minecraft/session,servicesHost=https://authserver.ely.by/services]
[11:01:53] [Render thread/INFO]: CAFixer is not available: java.lang.NoClassDefFoundError: com/turikhay/caf/util/Logger
[11:01:53] [Render thread/ERROR]: Mixin apply for mod skinshuffle failed SkinShuffle.mixins.json:accessor.YggdrasilUserApiServiceAccessor from mod skinshuffle -> com.mojang.authlib.yggdrasil.YggdrasilUserApiService: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching minecraftClient:Lcom/mojang/authlib/minecraft/client/MinecraftClient; in com/mojang/authlib/yggdrasil/YggdrasilUserApiService for SkinShuffle.mixins.json:accessor.YggdrasilUserApiServiceAccessor from mod skinshuffle->@Accessor[FIELD_GETTER]::getMinecraftClient()Lcom/mojang/authlib/minecraft/client/MinecraftClient; [INJECT Applicator Phase -> SkinShuffle.mixins.json:accessor.YggdrasilUserApiServiceAccessor from mod skinshuffle -> Apply Accessors ->  -> Locate -> SkinShuffle.mixins.json:accessor.YggdrasilUserApiServiceAccessor from mod skinshuffle->@Accessor[FIELD_GETTER]::getMinecraftClient()Lcom/mojang/authlib/minecraft/client/MinecraftClient;]
org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching minecraftClient:Lcom/mojang/authlib/minecraft/client/MinecraftClient; in com/mojang/authlib/yggdrasil/YggdrasilUserApiService for SkinShuffle.mixins.json:accessor.YggdrasilUserApiServiceAccessor from mod skinshuffle->@Accessor[FIELD_GETTER]::getMinecraftClient()Lcom/mojang/authlib/minecraft/client/MinecraftClient; [INJECT Applicator Phase -> SkinShuffle.mixins.json:accessor.YggdrasilUserApiServiceAccessor from mod skinshuffle -> Apply Accessors ->  -> Locate -> SkinShuffle.mixins.json:accessor.YggdrasilUserApiServiceAccessor from mod skinshuffle->@Accessor[FIELD_GETTER]::getMinecraftClient()Lcom/mojang/authlib/minecraft/client/MinecraftClient;]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:519) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:502) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:476) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1411) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1071) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:143) ~[authlib-6.0.52.2.jar:?]
	at net.minecraft.class_310.method_31382(class_310.java:825) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:464) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:223) ~[Fabric%201.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]
---- Minecraft Crash Report ----
// There are four lights!

Time: 2024-08-04 11:01:54
Description: Initializing game

### SkinShuffle version

lastest version, 1. 20. 4.

### Extra information

Idk

**Comment by IMB11** [comment]
I need the full logs uploaded to https://mclo.gs/ please

**Comment by Ggsgshhshs** [comment]
I’m sorry, I’m on vacation, I will send you all logs when I comeback!

Пн, 5 авг. 2024 г. в 3:35 PM, Calum ***@***.***>:
